   name: Docker Hub README Sync

   on:
     push:
       branches:
         - master # Trigger on pushes to the main branch

   jobs:
     sync-readme:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Sync README to Docker Hub
           uses: peter-evans/dockerhub-description@v4
           with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_PASSWORD }}
             repository: bcleonard/proxmox-qdevice

